### ISSUE TITLE
ImportError: No module named tld

### ISSUE THREAD

**Issue by Canorus** [LINKIWI/cloudflare-ddns-client#11]
I'm experiencing an weird error

![image](https://user-images.githubusercontent.com/7209435/54587168-9ba45780-4a62-11e9-863a-48c2bfc23f00.png)

As you can see above, `tld` module is installed alright, and I can import the module manually. But when I run `cloudflare-ddns` command it tells me no module named tld is there.

I reinstalled the package with `umask` set to `022` (as suggested [here](https://stackoverflow.com/a/11169137)) and added `/usr/local/lib` to **$PATH** where python module packages reside just in case, none of which worked.

Maybe little bit of help would be really appreciated. Thanks.

**Comment by LINKIWI** [comment]
Does it work if you invoke it as `python cloudflare-ddns`?

**Comment by Canorus** [comment]
manually fixing python to 3 fixed the problem. maybe module was only installed for python3. thanks for the help, and program.
