### ISSUE TITLE
Not updating all configured domain

### ISSUE THREAD

**Issue by marklai1998** [LINKIWI/cloudflare-ddns-client#15]
I have 2 domains under my Cloudflare account
and I followed the instruction to set it up
a.com,b.net
but when I do 
```
cloudflare-ddns --update-now
```

it only updates a.com and ignores b.net
Output: 
```
Updating the A record (ID .....) of (sub)domain a.com (ID ...) to 123.456.789.0.
DNS record is already up-to-date; taking no action
```

**Comment by marklai1998** [comment]
seems like it is because the program is looking for a root domain record
while I only have a.com and somthing.b.net in my configuration
thus the somthing.b.net is missed by the program

**Comment by LINKIWI** [comment]
Yes, I believe this is intended behavior, but I am open to accepting a pull request to make this behavior configurable.

**Comment by marklai1998** [comment]
I guess there is no better implementation in this stage
just update the readme
