### ISSUE TITLE
Fails to find A or CNAME records when name parameter does not perfectly match subdomain

### ISSUE THREAD

**Issue by point-source** [LINKIWI/cloudflare-ddns-client#16]
I have records which, when fetched by the api, report like so:

> type: A
> name: *.domain.com
> 
> type: CNAME
> name: www.domain.com
> 
> type: MX
> name: domain.com
> 
> type: TXT
> name: domain.com

The docs for this tool suggest that when I provide my domain name, I provide it in the format `domain.com`. However, the code uses a filter parameter with the api which filters against the "name" attribute of each record. This means, in my example, I only get the MX and TXT records returned so the A and CNAME records do not get returned to the program and therefore not updated.

There are multiple workarounds for this including modifying my config to be `domains=domain.com,*.domain.com,www.domain.com` but this feels somewhat unintuitive unless mentioned specifically in the docs. Alternatively, I can modify the script to search for those alternative subdomains automatically or I could remove the name param entirely but this could possibly have adverse affects for some users whereby records are unintentionally updated. (not sure)

I am starting this issue to discuss the most viable course of action to fix this. Happy to do a PR if you like. Thanks!

**Comment by LINKIWI** [comment]
I would prefer to not make the tool automatically guess the matching subdomains, since this "smart" behavior may be unexpected to many users. I've happy to accept a PR to fix the documentation though. Thank you for the detailed report.
