### ISSUE TITLE
Cloudflare protection turned off after --update-now

### ISSUE THREAD

**Issue by ghost** [LINKIWI/cloudflare-ddns-client#18]
Hi there, 

every time the --update-now command is ran manually or via crontab, the cloudflare protection is being turned off. 

I mean the cloud icon in the DNS section of cloudflare.com.
This is a very useful feature i want to always be enabled. It protects/hides my IP.

Is this behaivor intentional?

Best regards
cryllical

**Comment by LINKIWI** [comment]
Probably not intentional. Happy to accept a PR to change this behavior.

**Comment by ghost** [comment]
Hi, thanks for your quick response. 
I unfortunately don’t know how to program in Python and I’m not really familiar with the Cloudflare API. I’d be very grateful if you could fix this. I would even pay you since I rely on this tool.

**Comment by ghost** [comment]
Okay, i know why this is happening now.

It looks like the proxied parameter in the API is now defaulting to false, which is disabling the Cloudflare protection. Setting proxied = true in the api call will set the Cloudflare protection on when the record is updated.

**This line:**

`data=json.dumps({'type': record['type'], 'name': record['name'], 'content': ip_address}),`

will need to be changed to something like

`data=json.dumps({'type': record['type'], 'name': record['name'], 'content': ip_address, 'proxied':'true'})`

Best regards

**Comment by ghost** [comment]
**I finally figured it out!**

`data=json.dumps({'type': record['type'], 'name': record['name'], 'content': ip_address}),`

needs to be changed to

`data=json.dumps({'type': record['type'], 'name': record['name'], 'content': ip_address, 'proxied': True}),`
