### ISSUE TITLE
Domains are on DNS Only

### ISSUE THREAD

**Issue by jamie-stinson** [LINKIWI/cloudflare-ddns-client#23]
Every time DNS is updated all the hostnames are put back to 'DNS Only' and not 'Proxied'

**Comment by LINKIWI** [comment]
This should be fixed by #21. I'm not sure if the original PR author intends to continue work on it. Please feel free to pick it up and I'm happy to accept your contribution.

**Comment by marvinjuette** [comment]
I experience the same thing. Every morning I have to put all domains manually back to proxied mode

**Comment by Paul-Reed** [comment]
Is this project no longer supported Kevin @LINKIWI ?

**Comment by LINKIWI** [comment]
Hi, yes it is still supported, please send in a PR and I'd be happy to take a look at it

**Comment by marvinjuette** [comment]
Sorry, it was my mistake. After a `git pull` everything works perfectly fine. Now i even able to use tokens xD Sorry

**Comment by marvinjuette** [comment]
Im sorry, but the problem occurred again ;/
