### ISSUE TITLE
Some issue report

### ISSUE THREAD

**Issue by koopernick** [LINKIWI/cloudflare-ddns-client#33]
Hello,

Fresh install (ubuntu 18), when I launched => cloudflare-ddns --configure
it asked me for my api token and sub domain (nothing else).

When I tried to launch => cloudflare-ddns --update-now

=> Configuration file /root/.cloudflare-ddns not found or invalid! Did you run cloudflare-ddns --configure?

I had to manually check your code and edit the configure file to manually add : 

auth_type
email
api_key

because I only had "domains" in my configure file for some reason.

Also, this => https://api.ipify.org/?format=json
timed-out, had to use the http link.

Now it's working, I'm just letting you know about the issue I had.

Thanks for the script !

**Comment by ev3rest** [comment]
Thanks, also faced the issue and fixed it with your solution

**Comment by zaanposni** [comment]
Both, authorizing via Key and via Token are working for me. Did you get an error message while using `--configure`? 

Check that you are not confusing Key and Token: https://dash.cloudflare.com/profile/api-tokens There are two sections! 😄 (that was my mistake at the first try)

`http` versions are possible to implement but shouldn't be the default in my opinion. 

I will implement the latter.

**Comment by zaanposni** [comment]
Hey @koopernick,

please see #39 and #40. I improved the user dialog (which results in a safer creation of the config file) and the determination of the external address. 

I think you can close this issue now.
