### ISSUE TITLE
Improve feedback/error messages in cli

### ISSUE THREAD

**Issue by zaanposni** [LINKIWI/cloudflare-ddns-client#34]
Hey,

I have recently started to use your tool. 
However, there were a few things that bothered me.
If you do not mind, I would like to contribute and improve feed back messages in the CLI and various other stuff. <b>Feel free to assign me to this issue</b>.
Just posting this issue so noone else works on the same stuff at the same time 😄.

**Comment by LINKIWI** [comment]
Hello, contributions are always welcome and I'm happy to merge any improvements you may have. Thanks!

**Comment by zaanposni** [comment]
@LINKIWI Quick question, do you want to keep compatibility to python2 ?

**Comment by LINKIWI** [comment]
I have no strong opinion
