### ISSUE TITLE
request.get() results in 403

### ISSUE THREAD

**Issue by marvinjuette** [LINKIWI/cloudflare-ddns-client#36]
I have a problem with the token authentification. 
Everytime I run the script I got the message that I should check my login data. But they are correct. So I started to search where the authentification fails.

I found that
```python
zone_resp = requests.get(CLOUDFLARE_ZONE_QUERY_API, headers=auth, timeout=6, params={'per_page': 50, 'page': cur_page})
print(zone_resp)
```
is not working properly.
`zone_resp: <Response [403]>`

I have no clue why this is happening. If I find a fix to this problem I'll make a pull request.

**Comment by marvinjuette** [comment]
Fun fact:
```python
test_resp = requests.get("https://api.cloudflare.com/client/v4/user/tokens/verify", headers=auth, timeout=6)
print(test_resp)
```
works fine and returns:
`<Response [200]>`

**Comment by marvinjuette** [comment]
Ok somehow my permissions for the api token were wrong. :/

**Comment by zaanposni** [comment]
Already made a PR #35 that should provide detailed logging for those requests. Seems like common mistakes are 
- confusing key and token
- not applying all needed permissions
- not knowing what is wrong because of bad/incomplete feedback messages.

**Comment by marvinjuette** [comment]
yeah but the feedback messages from cloudflare are not bad too.

**Comment by zaanposni** [comment]
Yes cloudflare usually tells you what is wrong. My PR just got merged. 
Now, if a request fails, the CLI lists all errors it can identify. 
If you issues again, try the newest version of the `master` branch :)
