### ISSUE TITLE
update dns record fail

### ISSUE THREAD

**Issue by cras4202tw** [LINKIWI/cloudflare-ddns-client#45]
[root@localhost ~]# /usr/local/bin/cloudflare-ddns --update-now

This is the output
```
Found external IPv4: "1.164.249.xxx"
Listing all zones.
Finding all DNS records.
```
Actually still not updated

**Comment by zaanposni** [comment]
Hi @cras4202tw,
Can you share you config file? It should be located at `~/.cloudflare-ddns`
Mine looks like:
```
[Cloudflare DDNS]
auth_type = token
api_token = my_token
domains = cooldomain.com
```

Does your cloudflare look something like this?
![grafik](https://user-images.githubusercontent.com/24491035/80857636-ecb9df80-8c53-11ea-96f4-09a24a761dd0.png)



If you run `cloudflare-ddns --update-now`, the program just exits? This seems like there are no domains defined. In this case there is no output that would warn you.

**Comment by cras4202tw** [comment]
In fact, I tested the same output for token and key
I deployed more than 10 DDNS and suddenly failed together

```
[Cloudflare DDNS]
auth_type = key
email = cras4202tw@4rbj4.com
api_key = 486b70cec5358cd64d5XXXXXXXXXX
domains = XXXXXXp.crlab.io
```

**Comment by zaanposni** [comment]
As far as I can tell, you will not receive any further output if the domains you entered are valid, but there are no `A` or `AAAA` records found on your cloudflare.
Are you sure, that you have domains configured like I have in the image above?

**Comment by zaanposni** [comment]
Hey @cras4202tw,
I added detailed output that should handle your case.
Can you pull the newest version from the master branch and run the script again with using the `--debug` flag?

**Comment by cras4202tw** [comment]
Found the problem

For example, there is a reocrd in Cloudflare
```aaaa.com```
I used to set cloudflare-ddns-client to
```AAAA.com ```
can be updated normally

Change to lowercase ```aaaa.com``` in config
To update normally
